services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    networks:
      - app_network
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      - .env

networks:
  app_network:
    driver: bridge
